name: CD | Build-Test-Release

on:
  push:
    branches:
      - "main"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker Image Tag"
        required: false
        default: "dev"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push step
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ (github.event_name == 'release' && github.event.release.tag_name) || (github.event_name == 'workflow_dispatch' && github.event.inputs.image_tag) || 'dev' }}

  dev-test:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Tests
      - name: Run Tests
        if: github.event_name != 'release'
        id: run-tests
        uses: direlines/runpod-test-runner@v1.7
        with:
          image-tag: ghcr.io/${{ github.repository }}:${{ (github.event_name == 'release' && github.event.release.tag_name) || (github.event_name == 'workflow_dispatch' && github.event.inputs.image_tag) || 'dev' }}
          runpod-api-key: ${{ secrets.RUNPOD_API_KEY }}
          request-timeout: 600

      # Pass/Fail
      - name: Verify Tests
        env:
          TOTAL_TESTS: ${{ steps.run-tests.outputs.total-tests }}
          SUCCESSFUL_TESTS: ${{ steps.run-tests.outputs.succeeded }}
          RESULTS: ${{ steps.run-tests.outputs.results }}
        run: |
          echo "Total tests: $TOTAL_TESTS"
          echo "Successful tests: $SUCCESSFUL_TESTS"
          echo "Full results: $RESULTS"
          if [ "$TOTAL_TESTS" != "$SUCCESSFUL_TESTS" ]; then
              exit 1
          fi
